const express = require('express')
const router = express.Router()
const getUser = require('../utils/getUser')
const auth = require('../middleware/auth')

const getAll = require('../api/Product/getAll')
const preHandle = require('../api/Product/preHandle')
const create = require('../api/Product/create')
const update = require('../api/Product/update')
const getById = require('../api/Product/getById')
const deleteProduct = require('../api/Product/delete')
const search = require('../api/Product/search')
const getOne = require('../api/Product/getOne')
const filter = require('../api/Product/filter')

// router.post('/unlike/:postId', auth, getUser, controller.unlike)
// router.post('/like/:postId', auth, getUser, controller.like)
// router.get('/comment/:postId', controller.getComment)
// router.post('/comment/:postId', auth, getUser, controller.createComment)
// router.get('/create', auth, controller.getCategories)
router.get('/search/:slug', search)
router.post('/delete/:productId', auth, getUser, deleteProduct)
router.get('/update/:productId', auth, getUser, getById)
router.post('/update/:productId', auth, getUser, preHandle, update)
router.post('/create', auth, getUser, preHandle, create)
router.get('/', getAll)
router.get('/v1/filter', filter)
router.get('/:slug', getOne)

module.exports = router